import { AuthProvider } from "@/context/AuthContext";
import { DataProvider } from "@/context/DataContext";
import { Poppins, Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "../components/Navbar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});
export const metadata = {
  title: "Paywall App",
  description: "Generated by Miriam Abella",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <AuthProvider>
          <DataProvider>
            <Navbar></Navbar>
            <Toaster position="top-center" />
            {children}
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
